# Generated by Django 4.2.3 on 2023-07-25 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_alter_userprofile_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_identity_name', models.CharField(max_length=500)),
                ('net_profit', models.IntegerField()),
                ('total_attachment', models.IntegerField()),
                ('operating_expens', models.IntegerField()),
                ('name_operating_expense', models.CharField(max_length=500)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
