# Generated by Django 4.2.3 on 2023-07-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_financesettlement_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatingexpens',
            name='username',
        ),
    ]
