# Generated by Django 4.2.3 on 2023-07-26 03:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_operatingexpens_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='operatingexpens',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
