# Generated by Django 4.2.3 on 2023-07-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_operatingexpens_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financesettlement',
            name='percent_net_profit',
            field=models.IntegerField(),
        ),
    ]
