# Generated by Django 4.2.3 on 2023-07-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_financesettlement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettlement',
            name='slug_financesettlement',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
