# Generated by Django 4.2.3 on 2023-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_financesettlement_slug_financesettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettlement',
            name='is_completed',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
