# Generated by Django 4.2.3 on 2023-07-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_financesettlement_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=215)),
                ('user2', models.CharField(max_length=215)),
                ('message', models.JSONField(null=True)),
                ('slug_num', models.CharField(max_length=15)),
                ('date_public', models.DateTimeField(auto_now_add=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_username', models.CharField(blank=True, max_length=215, null=True)),
            ],
        ),
    ]
