# Generated by Django 4.2.3 on 2023-07-29 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0023_messagechat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagechat',
            name='date_public',
        ),
        migrations.RemoveField(
            model_name='messagechat',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='messagechat',
            name='last_username',
        ),
        migrations.RemoveField(
            model_name='messagechat',
            name='message',
        ),
        migrations.AlterField(
            model_name='messagechat',
            name='slug_num',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.RemoveField(
            model_name='messagechat',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='messagechat',
            name='user2',
        ),
        migrations.CreateModel(
            name='MessageSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='messagechat',
            name='user1',
            field=models.ManyToManyField(to='myapp.messagesender'),
        ),
        migrations.AddField(
            model_name='messagechat',
            name='user2',
            field=models.ManyToManyField(to='myapp.messagerecipient'),
        ),
    ]
