# Generated by Django 4.2.3 on 2023-07-29 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0024_remove_messagechat_date_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechat',
            name='user1_search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagechat',
            name='user2_search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='messagesender',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
