# Generated by Django 4.2.3 on 2023-07-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_messagermodel_remove_messagesender_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagechat',
            old_name='user1',
            new_name='user',
        ),
    ]
