# Generated by Django 4.2.3 on 2023-07-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_user1_messagechat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.messagermodel'),
        ),
    ]
