# Generated by Django 4.2.3 on 2023-07-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_messagechat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagermodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
