# Generated by Django 4.2.3 on 2023-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_messagermodel_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechat',
            name='is_read_num',
            field=models.IntegerField(default=0),
        ),
    ]
