# Generated by Django 4.2.3 on 2023-07-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_messagechat_is_read_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagechat',
            old_name='is_read_num',
            new_name='is_read_num_user1',
        ),
        migrations.AddField(
            model_name='messagechat',
            name='is_read_num_user2',
            field=models.IntegerField(default=0),
        ),
    ]
